### PR TITLE
A proposed fix so that one does not have to make a copy of a document fro

### PR DESCRIPTION
**Pull request by malteseduck**
A proposed fix so that one does not have to make a copy of a document from the database to modify it in-memory.  Search for "marklogic: document in-memory-update" in markmail.org to see details of problem (or http://markmail.org/search/?q=marklogic%3A%20document%20in-memory-update#query:marklogic%3A%20document%20in-memory-update+page:1+mid:4n6dmf52xmmiwhr7+state:results).

This seems to work, am I missing something?  Does this make it work better or is it more brittle and add any performance problems?

### CODE REVIEW

**Comment by eedeebee** [comment]
Hoping you can see Hunter's review comment https://github.com/marklogic/commons/pull/6#commitcomment-383040 - waiting for you to respond now.

-Eric

**Comment by malteseduck** [comment]
Whoops, the change for local-name() to name() was put in because we thought it was having problems preserving the namespaces because we weren't doing it right.  I just tested it with local-name() and it works just fine with namespaces so it can be put back to local-name().

As far as the other stuff, would this work better to preserve the document:
    .....
        else if (xdmp:node-kind($node) eq "document") then
            document {
                 mem:_process($node/node(), $modifierNodes, $newNode, $mode)
            }
        else
    .....

This seems to preserve the comments as well.  Truth be told I can't seem to get other PIs to even save using WebDAV, I have never tried any other way so I am not sure how.  I was trying to use this 

<?xml version="1.0"? encoding="UTF-8" standalone="yes"?>

to test but it always gets changed back to this:

<?xml version="1.0" encoding="UTF-8"?>

when I open it back up in WebDAV.  Thoughts?

**Comment by hunterhacker** [comment]
Thoughts on the attached code?

-jh-

**Comment by malteseduck** [comment]
Sorry, that was a little ambiguous.  What are your thoughts on:
1. The code, does that make things a little better so we can return what we get passed and we can preserve comments
2. What other PIs should we worry about, any suggestions on what can be done to handle them, if there is anything?

**Comment by hunterhacker** [comment]
The <?xml?> thing at the top isn't actually a PI, it's a declaration that uses PI-type syntax.

I sent you another version of the library (based on another lineage but with the same fixes and then a few others) but GitHub didn't pass it through.  That's the "Thoughts on the attached code?" comment above.  What's your direct email address?  I'll send it to you there.

**Comment by malteseduck** [comment]
the.maltese.duck@gmail.com

**Pull request closed without merging**
